import { StyleSheet } from 'react-native';

/** LoginPage.css renkleri ve ölçüleri */
export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#050505',
    justifyContent: 'center',
    padding: 24,
  },
  card: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    paddingTop: 40,
    paddingBottom: 32,
    paddingHorizontal: 36,
    borderRadius: 16,
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  logo: {
    width: 56,
    height: 56,
    alignSelf: 'center',
    marginBottom: 20,
    borderRadius: 14,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoMark: {
    fontSize: 26,
    fontWeight: '700',
    color: '#fff',
    fontFamily: 'serif',
  },
  title: {
    marginBottom: 8,
    fontSize: 22,
    fontWeight: '600',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  subtitle: {
    marginBottom: 28,
    fontSize: 14,
    color: '#737373',
    textAlign: 'center',
  },
  label: {
    fontSize: 12,
    color: '#a3a3a3',
    marginBottom: 6,
  },
  input: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: '#0a0a0a',
    color: '#fafafa',
    fontSize: 15,
    marginBottom: 16,
  },
  error: {
    marginBottom: 12,
    fontSize: 14,
    color: '#f87171',
  },
  submit: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#262626',
    alignItems: 'center',
  },
  submitDisabled: {
    opacity: 0.7,
  },
  submitText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 15,
  },
  footer: {
    marginTop: 24,
    textAlign: 'center',
    fontSize: 13,
    color: '#525252',
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  footerLink: {
    color: '#a3a3a3',
    fontSize: 13,
  },
  footerDot: {
    color: '#525252',
    opacity: 0.5,
  },
  footerMuted: {
    color: '#525252',
    opacity: 0.85,
    fontSize: 13,
  },
});
