import { StyleSheet } from 'react-native';

/** TimerPage.css renkleri ve ölçüleri */
export const dashboardStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#0c0c0e',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  brand: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0.4,
    color: '#fafafa',
  },
  nav: {
    flexDirection: 'row',
  },
  navLink: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    marginHorizontal: 2,
  },
  navLinkActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  navLinkText: {
    fontSize: 13,
    color: '#8e8ea0',
  },
  navLinkTextActive: {
    color: '#f4f4f5',
  },
  profileTrigger: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMenu: {
    position: 'absolute',
    top: 44,
    right: 0,
    minWidth: 160,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 6,
    zIndex: 20,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  profileItem: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  profileItemText: {
    fontSize: 14,
    color: '#1a1a1a',
  },
  profileItemDanger: {
    color: '#dc2626',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
    gap: 24,
  },
  panel: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: 'rgba(24, 24, 27, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  modes: {
    flexDirection: 'row',
    padding: 4,
    marginBottom: 8,
    borderRadius: 14,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  modeBtnActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  modeText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#71717a',
  },
  modeTextActive: {
    color: '#fafafa',
  },
  circTimer: {
    alignSelf: 'center',
    marginBottom: 8,
  },
  clock: {
    fontSize: 28,
    fontWeight: '500',
    textAlign: 'center',
    color: '#fafafa',
    marginBottom: 12,
    fontVariant: ['tabular-nums'],
  },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 24,
  },
  fab: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  field: {
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#71717a',
    marginBottom: 6,
  },
  input: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#fafafa',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
  },
  picker: {
    //color: '#fafafa',//
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
  },
  save: {
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#f4f4f5',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  saveDisabled: {
    opacity: 0.38,
  },
  saveText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#18181b',
  },
  msgErr: {
    marginTop: 8,
    fontSize: 13,
    color: '#f87171',
  },
  hint: {
    marginTop: 12,
    fontSize: 11,
    lineHeight: 16,
    color: '#52525b',
    textAlign: 'center',
  },
  log: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: 'rgba(24, 24, 27, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    minHeight: 200,
  },
  logHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  logTitle: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.3,
    color: '#e4e4e7',
  },
  logCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#71717a',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    overflow: 'hidden',
  },
  logEmpty: {
    paddingVertical: 24,
    fontSize: 14,
    lineHeight: 21,
    color: '#71717a',
    textAlign: 'center',
  },
  logEmptyErr: {
    color: '#f87171',
  },
  logItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    marginBottom: 8,
  },
  logName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#e4e4e7',
    lineHeight: 19,
    marginBottom: 4,
  },
  logMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
  },
  logMetaText: {
    fontSize: 12,
    color: '#71717a',
  },
  logDur: {
    color: '#a1a1aa',
  },
  logDot: {
    opacity: 0.5,
    color: '#71717a',
  },
  logDel: {
    padding: 6,
  },
  plannerBoard: {
    flexDirection: 'row',
    backgroundColor: '#e9e5d9',
    borderWidth: 1,
    borderColor: '#1a1a1a',
    borderRadius: 8,
    minHeight: 400,
    overflow: 'hidden',
  },
  plannerCol: {
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: '#1a1a1a',
  },
  plannerDay: {
    textAlign: 'center',
    paddingVertical: 12,
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a1a',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
  },
  plannerInput: {
    flex: 1,
    padding: 12,
    color: '#1a1a1a',
    fontSize: 13,
    textAlignVertical: 'top',
    minHeight: 120,
  },
});
